{
 "title": "Overview",
 "description": "See an overview of all Composer targets and any optionally monitored Linux servers",
 "tags": [ "overview" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "description": "Errors and warnings in the logs, over the selected time range.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(alert_level) (count_over_time({job=\"composerLogs\"} |~ \"^.* (Fatal|Error|Warning) \" | regexp `(?P<alert_level>Fatal|Error|Warning)` [3m]))",
     "legendFormat": "{{ alert_level }}"
    }
   ]
  },
  {
   "title": "Composer targets",
   "type": "table",
   "description": "An overview of all configured composer instances (in composerInstances.yml).",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (up{instance!~\".*:9100\"})"
    },
    {
     "expr": "label_replace(label_replace((sum by(instance, systemlabel, version, hostname) (composer_ext_alarms_currently_active)) OR on(instance) (sum by(instance, systemlabel, version, hostname) (last_over_time(composer_ext_alarms_currently_active[7d]))) OR on(instance) (sum by(instance) (up{instance!~\".*:9100\"}) * 0), \"host_display\", \"$1\", \"instance\", \"(.*)\"), \"host_display\", \"$1\", \"systemlabel\", \"(.+)\")"
    },
    {
     "expr": "(sum by(instance) (composer_ext_average_processing_usage_10k_frames)) OR on(instance) (sum by(instance) (up{instance!~\".*:9100\"}) * 0)"
    }
   ]
  },
  {
   "title": "Most common Critical, Errors & Warnings",
   "type": "table",
   "description": "Most common errors and warnings, by type and System Label",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, sum by(log_level, error_message)(count_over_time({job=\"composerLogs\"} | regexp \"(?P<log_level>Fatal|Error|Warning)\\\\s+\\\\(\\\\d+\\\\)\\\\s+(?P<error_message>.+)\" | log_level=~\"Fatal|Error|Warning\" | error_message != \"\" [$__range])))",
     "legendFormat": "{{<error_message>}}"
    }
   ]
  },
  {
   "title": "Server targets",
   "type": "table",
   "description": "An overview of configured Linux servers, with the optional server stats plugin.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(up{instance =~\".*:9100\"}) by (instance)"
    },
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(node_load5[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_time_seconds - node_boot_time_seconds) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}